// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: opentelemetry/proto/resource/v1/resource.proto
// Protobuf Java Version: 4.33.1

package io.opentelemetry.proto.resource.v1;

@com.google.protobuf.Generated
public final class ResourceProto extends com.google.protobuf.GeneratedFile {
  private ResourceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ResourceProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_resource_v1_Resource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_opentelemetry_proto_resource_v1_Resource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.opentelemetry/proto/resource/v1/resour" +
      "ce.proto\022\037opentelemetry.proto.resource.v" +
      "1\032*opentelemetry/proto/common/v1/common." +
      "proto\"\250\001\n\010Resource\022;\n\nattributes\030\001 \003(\0132\'" +
      ".opentelemetry.proto.common.v1.KeyValue\022" +
      " \n\030dropped_attributes_count\030\002 \001(\r\022=\n\013ent" +
      "ity_refs\030\003 \003(\0132(.opentelemetry.proto.com" +
      "mon.v1.EntityRefB\203\001\n\"io.opentelemetry.pr" +
      "oto.resource.v1B\rResourceProtoP\001Z*go.ope" +
      "ntelemetry.io/proto/otlp/resource/v1\252\002\037O" +
      "penTelemetry.Proto.Resource.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opentelemetry.proto.common.v1.CommonProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_resource_v1_Resource_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_opentelemetry_proto_resource_v1_Resource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_opentelemetry_proto_resource_v1_Resource_descriptor,
        new java.lang.String[] { "Attributes", "DroppedAttributesCount", "EntityRefs", });
    descriptor.resolveAllFeaturesImmutable();
    io.opentelemetry.proto.common.v1.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
