// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: opentelemetry/proto/metrics/v1/metrics.proto
// Protobuf Java Version: 4.33.1

package io.opentelemetry.proto.metrics.v1;

@com.google.protobuf.Generated
public interface SummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.metrics.v1.Summary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The time series data points.
   * Note: Multiple time series may be included (same timestamp, different attributes).
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.SummaryDataPoint data_points = 1;</code>
   */
  java.util.List<io.opentelemetry.proto.metrics.v1.SummaryDataPoint> 
      getDataPointsList();
  /**
   * <pre>
   * The time series data points.
   * Note: Multiple time series may be included (same timestamp, different attributes).
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.SummaryDataPoint data_points = 1;</code>
   */
  io.opentelemetry.proto.metrics.v1.SummaryDataPoint getDataPoints(int index);
  /**
   * <pre>
   * The time series data points.
   * Note: Multiple time series may be included (same timestamp, different attributes).
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.SummaryDataPoint data_points = 1;</code>
   */
  int getDataPointsCount();
  /**
   * <pre>
   * The time series data points.
   * Note: Multiple time series may be included (same timestamp, different attributes).
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.SummaryDataPoint data_points = 1;</code>
   */
  java.util.List<? extends io.opentelemetry.proto.metrics.v1.SummaryDataPointOrBuilder> 
      getDataPointsOrBuilderList();
  /**
   * <pre>
   * The time series data points.
   * Note: Multiple time series may be included (same timestamp, different attributes).
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.metrics.v1.SummaryDataPoint data_points = 1;</code>
   */
  io.opentelemetry.proto.metrics.v1.SummaryDataPointOrBuilder getDataPointsOrBuilder(
      int index);
}
